name: Run Email Script

on:
  schedule:
    - cron: '0 1 29 4 *'  # This cron job runs at 1:00 AM on April 29th

jobs:
  run-email-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun i

      - name: Run email script
        run: bun run email