name: Run Email Script

on:
  schedule:
    - cron: '0 0 23 5 *'  # This cron job runs at 00:00 on May 23rd every year

jobs:
  run-email-script:
    runs-on: ubuntu-latest
    if: ${{ contains('2025', format('{0:yyyy}', github.event.schedule)) }}  # Only run in 2025
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun i

      - name: Run email script
        run: bun run email